export const electricSvgList = [
  {
    name: '二极管',
    icon: 'svg/二极管.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/二极管.svg',
      tags: ['Diode'],
      electricTypeCode: 'Diode',
      electricName: '',
    },
  },
  {
    name: '半圆-封口',
    icon: 'svg/半圆-封口.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/半圆-封口.svg',
      tags: [],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '半圆-开口',
    icon: 'svg/半圆-开口.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/半圆-开口.svg',
      tags: [],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '声音-扬声器',
    icon: 'svg/声音-扬声器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/声音-扬声器.svg',
      tags: [],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '声音-蜂鸣器',
    icon: 'svg/声音-蜂鸣器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/声音-蜂鸣器.svg',
      tags: [],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-三位置-1位',
    icon: 'svg/开关-三位置-1位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-三位置-1位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-三位置-2位',
    icon: 'svg/开关-三位置-2位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-三位置-2位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-三位置-3位',
    icon: 'svg/开关-三位置-3位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-三位置-3位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-单刀双掷-中间位',
    icon: 'svg/开关-单刀双掷-中间位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-单刀双掷-中间位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-单刀双掷-右位',
    icon: 'svg/开关-单刀双掷-右位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-单刀双掷-右位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-单刀双掷-左位',
    icon: 'svg/开关-单刀双掷-左位.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-单刀双掷-左位.svg',
      tags: ['MultipleContact'],
      electricTypeCode: 'MultipleContact',
      electricName: '',
    },
  },
  {
    name: '开关-惯性开关-断开',
    icon: 'svg/开关-惯性开关-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-惯性开关-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-惯性开关-闭合',
    icon: 'svg/开关-惯性开关-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-惯性开关-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-按钮-断开',
    icon: 'svg/开关-按钮-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-按钮-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-按钮-闭合',
    icon: 'svg/开关-按钮-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-按钮-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-断路器-断开',
    icon: 'svg/开关-断路器-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-断路器-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-断路器-闭合',
    icon: 'svg/开关-断路器-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-断路器-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自复旋转开关-断开',
    icon: 'svg/开关-自复旋转开关-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自复旋转开关-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自复旋转开关-闭合',
    icon: 'svg/开关-自复旋转开关-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自复旋转开关-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自锁按钮-断开',
    icon: 'svg/开关-自锁按钮-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自锁按钮-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自锁按钮-闭合',
    icon: 'svg/开关-自锁按钮-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自锁按钮-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自锁旋转开关-断开',
    icon: 'svg/开关-自锁旋转开关-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自锁旋转开关-断开.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-自锁旋转开关-闭合',
    icon: 'svg/开关-自锁旋转开关-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-自锁旋转开关-闭合.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '开关-通用开关-断开',
    icon: 'svg/开关-通用开关-断开.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-通用开关-断开.svg',
      tags: ['Switch'],
      electricTypeCode: 'Switch',
      electricName: '',
    },
  },
  {
    name: '开关-通用开关-闭合',
    icon: 'svg/开关-通用开关-闭合.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/开关-通用开关-闭合.svg',
      tags: ['Switch'],
      electricTypeCode: 'Switch',
      electricName: '',
    },
  },
  {
    name: '指示灯',
    icon: 'svg/指示灯.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/指示灯.svg',
      tags: ['Lamp'],
      electricTypeCode: 'Lamp',
      electricName: '',
    },
  },
  {
    name: '测量-电压表',
    icon: 'svg/测量-电压表.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/测量-电压表.svg',
      tags: ['VProbe'],
      electricTypeCode: 'VProbe',
      electricName: '',
    },
  },
  {
    name: '测量-电流表',
    icon: 'svg/测量-电流表.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/测量-电流表.svg',
      tags: ['IProbe'],
      electricTypeCode: 'IProbe',
      electricName: '',
    },
  },
  {
    name: '电动机-三相',
    icon: 'svg/电动机-三相.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电动机-三相.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电容器',
    icon: 'svg/电容器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电容器.svg',
      tags: ['C'],
      electricTypeCode: 'C',
      electricName: '',
    },
  },
  {
    name: '电感-变压器',
    icon: 'svg/电感-变压器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电感-变压器.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电感-绕组-短',
    icon: 'svg/电感-绕组-短.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电感-绕组-短.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电感-绕组-长',
    icon: 'svg/电感-绕组-长.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电感-绕组-长.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电源-接地',
    icon: 'svg/电源-接地.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电源-接地.svg',
      tags: ['GND'],
      electricTypeCode: 'GND',
      electricName: '',
    },
  },
  {
    name: '电源-电池组',
    icon: 'svg/电源-电池组.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电源-电池组.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电源-直流电源',
    icon: 'svg/电源-直流电源.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电源-直流电源.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '电磁阀',
    icon: 'svg/电磁阀.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电磁阀.svg',
      tags: ['ElectromagneticValve'],
      electricTypeCode: 'ElectromagneticValve',
      electricName: '',
    },
  },
  {
    name: '电阻',
    icon: 'svg/电阻.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/电阻.svg',
      tags: ['R'],
      electricTypeCode: 'R',
      electricName: '',
    },
  },
  {
    name: '端子-环形',
    icon: 'svg/端子-环形.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/端子-环形.svg',
      tags: ['TerminalsXT'],
      electricTypeCode: 'TerminalsXT',
      electricName: '',
    },
  },
  {
    name: '端子-实心',
    icon: 'svg/端子-实心.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/端子-实心.svg',
      tags: ['TerminalsXT'],
      electricTypeCode: 'TerminalsXT',
      electricName: '',
    },
  },
  {
    name: '继电器-中间继电器-折线连接二极管',
    icon: 'svg/继电器-中间继电器-折线连接二极管.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-中间继电器-折线连接二极管.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '继电器-中间继电器-折线连接电阻',
    icon: 'svg/继电器-中间继电器-折线连接电阻.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-中间继电器-折线连接电阻.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '继电器-中间继电器',
    icon: 'svg/继电器-中间继电器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-中间继电器.svg',
      tags: ['Coil'],
      electricTypeCode: 'Coil',
      electricName: '',
    },
  },
  {
    name: '继电器-双位置',
    icon: 'svg/继电器-双位置.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-双位置.svg',
      tags: ['DoubleCoil'],
      electricTypeCode: 'DoubleCoil',
      electricName: '',
    },
  },
  {
    name: '继电器-失电延时',
    icon: 'svg/继电器-失电延时.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-失电延时.svg',
      tags: ['CoilOffDelay'],
      electricTypeCode: 'CoilOffDelay',
      electricName: '',
    },
  },
  {
    name: '继电器-得电延时',
    icon: 'svg/继电器-得电延时.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/继电器-得电延时.svg',
      tags: ['CoilOnDelay'],
      electricTypeCode: 'CoilOnDelay',
      electricName: '',
    },
  },
  {
    name: '跨接线',
    icon: 'svg/跨接线.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/跨接线.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '输入输出',
    icon: 'svg/输入输出.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/输入输出.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '连接端子-插针针孔',
    icon: 'svg/连接端子-插针针孔.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/连接端子-插针针孔.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
  {
    name: '避雷器',
    icon: 'svg/避雷器.svg',
    data: {
      text: '',
      // width: 100,
      // height: 100,
      name: 'image',
      image: 'svg/避雷器.svg',
      tags: [''],
      electricTypeCode: '',
      electricName: '',
    },
  },
];
